/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'domain-management',
    path: '/domain-management',
    component: 'layout.base',
    meta: {
      title: 'domain-management',
      i18nKey: 'route.domain-management',
      icon: 'mdi:web',
      order: 4,
      roles: ['admin']
    },
    children: [
      {
        name: 'domain-management_account',
        path: '/domain-management/account',
        component: 'view.domain-management_account',
        meta: {
          title: 'domain-management_account',
          i18nKey: 'route.domain-management_account',
          icon: 'mdi:account-key',
          roles: ['admin']
        }
      },
      {
        name: 'domain-management_list',
        path: '/domain-management/list',
        component: 'view.domain-management_list',
        meta: {
          title: 'domain-management_list',
          i18nKey: 'route.domain-management_list',
          icon: 'mdi:list-box',
          roles: ['admin']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system-settings',
    path: '/system-settings',
    component: 'layout.base',
    meta: {
      title: 'system-settings',
      i18nKey: 'route.system-settings',
      icon: 'mdi:cog-outline',
      order: 2,
      roles: ['admin']
    },
    children: [
      {
        name: 'system-settings_basic',
        path: '/system-settings/basic',
        component: 'view.system-settings_basic',
        meta: {
          title: 'system-settings_basic',
          i18nKey: 'route.system-settings_basic',
          icon: 'mdi:cog',
          roles: ['admin']
        }
      },
      {
        name: 'system-settings_email',
        path: '/system-settings/email',
        component: 'view.system-settings_email',
        meta: {
          title: 'system-settings_email',
          i18nKey: 'route.system-settings_email'
        }
      }
    ]
  },
  {
    name: 'user-management',
    path: '/user-management',
    component: 'layout.base',
    meta: {
      title: 'user-management',
      i18nKey: 'route.user-management',
      icon: 'mdi:account-group-outline',
      order: 3,
      roles: ['admin']
    },
    children: [
      {
        name: 'user-management_list',
        path: '/user-management/list',
        component: 'view.user-management_list',
        meta: {
          title: 'user-management_list',
          i18nKey: 'route.user-management_list',
          icon: 'mdi:account-multiple',
          roles: ['admin']
        }
      }
    ]
  }
];
